import { test, expect } from '@playwright/test'
import express from 'express'
import { createApp } from '../server/app'
import { Store } from '../server/store'
import { PrivateStorage } from '../server/storage'
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { resolve, join, dirname } from 'node:path'
import { pathToFileURL } from 'node:url'
import { PDFDocument } from 'pdf-lib'
import { unzipSync } from 'fflate'
import type { Server } from 'node:http'
let server:Server,store:Store,storage:PrivateStorage,root:string
const origin='http://127.0.0.1:4181'
test.beforeAll(async()=>{
  root=await mkdtemp(join(tmpdir(),'sdf-browser-'));store=new Store(undefined,root);await store.init();storage=new PrivateStorage(join(root,'blobs'))
  const app=createApp(store,storage,{dev:true,origin});app.use(express.static(resolve('dist')));app.get('/{*path}',(_req,res)=>res.sendFile(resolve('dist/index.html')))
  server=app.listen(4181,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r))
})
test.afterAll(async()=>{await new Promise<void>(r=>server.close(()=>r()));await store.close();await rm(root,{recursive:true,force:true})})
test('complete desktop workflow, dark theme, responsive layout, and offline file viewer',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto(origin);await expect(page.getByRole('heading',{name:'Productions',exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/home.png',fullPage:true})
  await page.getByRole('button',{name:'Create production',exact:true}).click()
  await page.getByRole('textbox',{name:'Production name',exact:true}).fill('First document production')
  await page.getByRole('textbox',{name:'Matter / client',exact:true}).fill('Sample matter · Synthetic documents')
  await page.getByRole('dialog').getByRole('button',{name:'Create production',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Source documents',exact:true})).toBeVisible()
  const pdf=await PDFDocument.create();pdf.addPage().drawText('Synthetic banking records — UI verification'.replace('—','-'),{x:50,y:700});pdf.addPage().drawText('Synthetic second page',{x:50,y:700})
  const data=Buffer.from(await pdf.save())
  await page.locator('input[type=file]').setInputFiles([{name:'Bank records #1.pdf',mimeType:'application/pdf',buffer:data},{name:'Financial statements.pdf',mimeType:'application/pdf',buffer:data}])
  await expect(page.getByText('2 PDFs added.',{exact:false})).toBeVisible()
  await page.screenshot({path:'test-results/documents.png',fullPage:true})
  await page.getByRole('button',{name:'Continue to Bates'}).click()
  await page.getByRole('button',{name:'Apply Bates labels',exact:true}).click()
  const progressDialog=page.getByRole('dialog',{name:'Bates labeling complete',exact:true})
  await expect(progressDialog).toBeVisible()
  await expect(progressDialog.getByRole('progressbar')).toHaveAttribute('value','4')
  await page.screenshot({path:'test-results/bates-progress.png',fullPage:true})
  await progressDialog.getByRole('button',{name:'Continue to Index & Tags',exact:true}).click()
  await page.getByRole('textbox',{name:'Description for Bank records #1.pdf',exact:true}).fill('Monthly bank statements')
  await page.getByRole('textbox',{name:'Description for Bank records #1.pdf',exact:true}).press('Tab')
  await expect(page.getByRole('status').filter({hasText:'Saved.'})).toBeVisible()
  await page.getByRole('button',{name:'Manage tags',exact:true}).click()
  await page.getByRole('textbox',{name:'New tag name'}).fill('Bank Records')
  await page.getByRole('button',{name:'Create tag',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Rename tag Bank Records'})).toBeVisible()
  await page.getByRole('button',{name:'Close tag manager'}).click()
  await page.getByRole('checkbox',{name:'Select all visible documents',exact:true}).check()
  await page.getByRole('combobox',{name:'Tag to apply'}).selectOption({label:'Bank Records'})
  await page.getByRole('button',{name:'Apply tag',exact:true}).click()
  await expect(page.getByRole('status').filter({hasText:'Saved.'})).toBeVisible()
  await page.screenshot({path:'test-results/index-and-tags.png',fullPage:true})
  await page.getByRole('button',{name:'Continue to Validate',exact:true}).click()
  await page.getByRole('button',{name:'Run validation'}).click()
  await expect(page.getByText('0 Bates gaps',{exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/validation.png',fullPage:true})
  await page.getByRole('button',{name:'Viewer',exact:true}).click()
  await expect(page.getByRole('img',{name:'Bank records #1, page 1'})).toHaveAttribute('data-rendered','true')
  await page.getByRole('button',{name:'Next PDF page',exact:true}).click()
  await expect(page.getByRole('img',{name:'Bank records #1, page 2'})).toHaveAttribute('data-rendered','true')
  const viewport=page.viewportSize()!
  const bounds=await page.locator('.viewer').boundingBox();expect(bounds!.y).toBeLessThan(230);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(viewport.height)
  const separator=page.getByRole('separator',{name:'Resize document index'}),handle=await separator.boundingBox()
  const oldWidth=(await page.locator('.viewer-index').boundingBox())!.width
  await page.mouse.move(handle!.x+4,handle!.y+60);await page.mouse.down();await page.mouse.move(handle!.x+104,handle!.y+60,{steps:5});await page.mouse.up()
  await expect.poll(async()=>(await page.locator('.viewer-index').boundingBox())!.width).toBeGreaterThan(oldWidth+70)
  await separator.focus();await page.keyboard.press('ArrowLeft')
  const savedSplit=await separator.getAttribute('aria-valuenow')
  await page.getByRole('button',{name:'Hide document index'}).click();await expect(page.locator('.viewer-index')).toBeHidden()
  await page.getByRole('button',{name:'Show document index'}).click();await expect(separator).toHaveAttribute('aria-valuenow',savedSplit!)
  const canvas=page.locator('.canvas-scroll canvas')
  await expect(canvas).toHaveAttribute('data-rendered','true')
  const fitPageHeight=(await canvas.boundingBox())!.height
  const available=(await page.locator('.canvas-scroll').boundingBox())!.height
  expect(fitPageHeight).toBeLessThanOrEqual(available)
  await page.getByRole('combobox',{name:'PDF fit',exact:true}).selectOption('width')
  await expect(canvas).toHaveAttribute('data-rendered','true')
  await expect.poll(async()=>(await canvas.boundingBox())!.height).toBeGreaterThan(fitPageHeight)
  await page.getByRole('combobox',{name:'PDF fit',exact:true}).selectOption('page')
  await expect(canvas).toHaveAttribute('data-rendered','true')
  await page.screenshot({path:'test-results/viewer.png',fullPage:true})
  await page.locator('.canvas-scroll').evaluate(element=>{element.scrollTop=element.scrollHeight})
  await page.locator('.pdf-pane').screenshot({path:'test-results/bates-preview.png'})
  await page.getByRole('searchbox').fill('SDF_000004')
  await expect(page.locator('.viewer-row')).toHaveCount(1)
  await expect(page.locator('.viewer-row')).toContainText('Financial statements')
  await page.getByRole('combobox',{name:'Theme',exact:true}).selectOption('dark')
  await page.screenshot({path:'test-results/dark.png',fullPage:true})
  await page.getByRole('combobox',{name:'Theme',exact:true}).selectOption('light')
  await page.getByRole('navigation',{name:'Production workflow'}).getByRole('button',{name:/Publish/}).click()
  await page.getByRole('button',{name:'Publish internal viewer',exact:true}).click()
  await expect(page.getByRole('button',{name:'Copy link',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Generate indexed PDF',exact:true}).click()
  await expect(page.getByRole('status').filter({hasText:'Indexed PDF is ready'})).toBeVisible()
  await page.getByRole('button',{name:'Generate offline package'}).click()
  await expect(page.getByRole('status').filter({hasText:'Offline ZIP is ready'})).toBeVisible()
  await page.screenshot({path:'test-results/publish.png',fullPage:true})
  const production=(await store.all())[0];const entry=production.exports.find(e=>e.kind==='offline')!
  const files=unzipSync(await storage.get(entry.key!))
  const offlineRoot=join(root,'offline');for(const [name,bytes] of Object.entries(files)){const file=join(offlineRoot,name);await mkdir(dirname(file),{recursive:true});await writeFile(file,bytes)}
  const offline=await browser.newPage();const external:string[]=[];offline.on('request',req=>{if(/^https?:/.test(req.url()))external.push(req.url())});await offline.goto(pathToFileURL(join(offlineRoot,'Production/index.html')).href)
  await expect(offline.locator('.doc')).toHaveCount(2);await offline.locator('#search').fill('SDF_000004');await expect(offline.locator('.doc')).toHaveCount(1);await expect(offline.locator('#open')).toHaveAttribute('href',/^PDFs\//)
  const offlineErrors:string[]=[];offline.on('pageerror',e=>offlineErrors.push(e.message))
  const offlineBounds=await offline.locator('main').boundingBox();expect(offlineBounds!.y).toBeLessThan(160)
  const offlineSeparator=offline.getByRole('separator',{name:'Resize document index'})
  const before=(await offline.locator('#index').boundingBox())!.width
  const grip=await offlineSeparator.boundingBox();await offline.mouse.move(grip!.x+4,grip!.y+60);await offline.mouse.down();await offline.mouse.move(grip!.x+94,grip!.y+60,{steps:5});await offline.mouse.up()
  await expect.poll(async()=>(await offline.locator('#index').boundingBox())!.width).toBeGreaterThan(before+60)
  await offlineSeparator.focus();await offline.keyboard.press('ArrowRight')
  await offline.getByRole('button',{name:'Hide document index'}).click();await expect(offline.locator('#index')).toBeHidden()
  await offline.getByRole('button',{name:'Show document index'}).click();await expect(offline.locator('#index')).toBeVisible()
  await offline.getByRole('combobox',{name:'PDF fit',exact:true}).selectOption('width');await expect(offline.locator('#preview')).toHaveAttribute('src',/#view=FitH$/)
  await offline.getByRole('combobox',{name:'PDF fit',exact:true}).selectOption('page');await expect(offline.locator('#preview')).toHaveAttribute('src',/#view=Fit$/)
  await offline.screenshot({path:'test-results/offline.png',fullPage:true});expect(external).toEqual([]);expect(offlineErrors).toEqual([]);await offline.close()
  await page.getByRole('button',{name:'View',exact:true}).click()
  await expect(page.locator('.attorney')).toBeVisible();await expect(page.getByRole('button',{name:'Bates',exact:true})).toHaveCount(0)
  await page.reload();await expect(page.getByRole('heading',{name:'First document production',exact:true})).toBeVisible()
  await expect(page.getByRole('separator',{name:'Resize document index'})).toHaveAttribute('aria-valuenow',savedSplit!)
  await expect(page.locator('.canvas-scroll canvas')).toHaveAttribute('data-rendered','true')
  await page.screenshot({path:'test-results/published-viewer.png',fullPage:true})
  await page.setViewportSize({width:760,height:900});await page.screenshot({path:'test-results/tablet.png',fullPage:true})
  await page.locator('.topbar .brand-link').click()
  await expect(page.getByRole('heading',{name:'Productions',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'First document production',exact:true}).click()
  await page.locator('summary').filter({hasText:'Production details'}).click()
  await page.getByRole('button',{name:'Delete production',exact:true}).click()
  const deletion=page.getByRole('dialog',{name:'Delete production?'})
  await expect(deletion.getByRole('button',{name:'Delete production',exact:true})).toBeDisabled()
  await deletion.getByRole('button',{name:'Cancel',exact:true}).click()
  await expect(page.getByRole('heading',{name:'First document production',exact:true})).toBeVisible()
  await page.locator('.sidebar .brand-link').click()
  await expect(page.getByRole('heading',{name:'Productions',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Delete First document production',exact:true}).click()
  await deletion.getByRole('textbox',{name:'Type the production name to confirm'}).fill('First document production')
  await deletion.getByRole('button',{name:'Delete production',exact:true}).click()
  await expect(deletion).toBeHidden()
  await expect(page.getByText('Production deleted.',{exact:false})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading',{name:'A clear path from documents to production.'})).toBeVisible()
  await expect(page.getByRole('button',{name:'First document production',exact:true})).toHaveCount(0)
  expect(errors).toEqual([])
})
