import { useEffect, useRef, useState } from 'react'
import { ChevronRight, Plus, Tags, Trash2, X } from 'lucide-react'
import type { Production, ProductionDocument } from '../shared/model'
import { matchesDocument } from '../shared/model'
type Action=(body:unknown,message?:string)=>Promise<void>
export default function IndexAndTags({p,action,busy,error,next}:{p:Production;action:Action;busy:boolean;error:string;next:()=>void}) {
  const [query,setQuery]=useState(''),[filter,setFilter]=useState(''),[sort,setSort]=useState('bates'),[metadata,setMetadata]=useState(true)
  const [selected,setSelected]=useState<string[]>([]),[tag,setTag]=useState(''),[managing,setManaging]=useState(false),[name,setName]=useState('')
  const dialog=useRef<HTMLDialogElement>(null)
  useEffect(()=>{if(managing)dialog.current?.showModal();else dialog.current?.close()},[managing])
  const docs=p.documents.filter(d=>(!filter||d.tagIds.includes(filter))&&matchesDocument(d,query,p.tags)).sort((a,b)=>sort==='name'?a.displayName.localeCompare(b.displayName):0)
  const visibleIds=docs.map(d=>d.id),all=docs.length>0&&docs.every(d=>selected.includes(d.id))
  function update(d:ProductionDocument,key:string,value:string){if(value!==d[key as keyof ProductionDocument])void action({type:'document',id:d.id,displayName:d.displayName,description:d.description,documentDate:d.documentDate,[key]:value})}
  return <section className="panel"><div className="section-heading"><div><h2>Index & Tags</h2><p className="muted">Edit metadata and organize documents in one place. Field edits save when you leave the field.</p></div><div className="button-row"><button onClick={()=>setManaging(true)}><Tags/>Manage tags</button><button className="primary" disabled={busy} onClick={next}>Continue to Validate<ChevronRight/></button></div></div>
    <div className="table-toolbar"><input className="index-search" type="search" aria-label="Search index" placeholder="Search names, Bates numbers, descriptions, or tags" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter by tag" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All tags</option>{p.tags.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select aria-label="Index sort order" value={sort} onChange={e=>setSort(e.target.value)}><option value="bates">Bates order</option><option value="name">Document name</option></select><label className="checkbox-label"><input type="checkbox" checked={metadata} onChange={e=>setMetadata(e.target.checked)}/>Metadata columns</label></div>
    <div className="selection-bar"><span>{selected.length} selected{selected.some(id=>!visibleIds.includes(id))?' (includes hidden rows)':''}</span><select aria-label="Tag to apply" value={tag} onChange={e=>setTag(e.target.value)}><option value="">Choose tag</option>{p.tags.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button disabled={!p.tags.some(t=>t.id===tag)||!selected.length} onClick={()=>void action({type:'tag-apply',id:tag,ids:selected})}>Apply tag</button><button disabled={!p.tags.some(t=>t.id===tag)||!selected.length} onClick={()=>void action({type:'tag-apply',id:tag,ids:selected,remove:true})}>Remove tag</button>{selected.length>0&&<button onClick={()=>setSelected([])}>Clear selection</button>}</div>
    <div className="table-scroll"><table className="index-table"><thead><tr><th><input type="checkbox" aria-label="Select all visible documents" checked={all} onChange={()=>setSelected(all?selected.filter(id=>!visibleIds.includes(id)):[...new Set([...selected,...visibleIds])])}/></th><th>Document name</th><th>Beginning Bates</th><th>Ending Bates</th><th>Pages</th>{metadata&&<><th>Description</th><th>Document date</th></>}<th>Tags</th></tr></thead><tbody>{docs.map(d=><tr key={d.id+':'+p.revision}><td><input type="checkbox" aria-label={`Select ${d.originalName}`} checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(id=>id!==d.id))}/></td><td><input aria-label={`Name for ${d.originalName}`} defaultValue={d.displayName} onBlur={e=>update(d,'displayName',e.target.value)}/></td><td className="numeric">{d.firstBates||'—'}</td><td className="numeric">{d.lastBates||'—'}</td><td>{d.pageCount}</td>{metadata&&<><td><input aria-label={`Description for ${d.originalName}`} defaultValue={d.description} placeholder="Add description" onBlur={e=>update(d,'description',e.target.value)}/></td><td><input aria-label={`Date for ${d.originalName}`} type="date" defaultValue={d.documentDate} onBlur={e=>update(d,'documentDate',e.target.value)}/></td></>}<td><div className="tag-chips">{p.tags.filter(t=>d.tagIds.includes(t.id)).map(t=><span key={t.id}>{t.name}<button className="tag-remove" aria-label={`Remove ${t.name} from ${d.displayName}`} onClick={()=>void action({type:'tag-apply',id:t.id,ids:[d.id],remove:true})}><X/></button></span>)}</div></td></tr>)}</tbody></table></div>{!docs.length&&<div className="empty">No matching documents. Add PDFs or adjust your filters.</div>}
    <dialog ref={dialog} aria-labelledby="manage-tags-title" onCancel={e=>{if(busy)e.preventDefault();else setManaging(false)}}><div className="dialog-heading"><h2 id="manage-tags-title">Manage tags</h2><button className="icon" disabled={busy} aria-label="Close tag manager" onClick={()=>setManaging(false)}><X/></button></div><p className="muted">Changes apply to this production. Existing published snapshots stay unchanged.</p>{error&&<p role="alert" className="danger">{error}</p>}<fieldset disabled={busy} className="workspace"><form className="button-row" onSubmit={e=>{e.preventDefault();void action({type:'tag-create',name})}}><input aria-label="New tag name" placeholder="New tag name" value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/><button><Plus/>Create tag</button></form><div className="tag-list">{p.tags.map(t=><div key={t.id+':'+t.name}><Tags/><input aria-label={`Rename tag ${t.name}`} defaultValue={t.name} onBlur={e=>{if(e.target.value!==t.name)void action({type:'tag-rename',id:t.id,name:e.target.value})}}/><span className="count">{p.documents.filter(d=>d.tagIds.includes(t.id)).length}</span><button className="icon" aria-label={`Delete tag ${t.name}`} onClick={()=>{if(confirm(`Delete “${t.name}” and remove it from workspace documents?`))void action({type:'tag-delete',id:t.id})}}><Trash2/></button></div>)}</div></fieldset></dialog>
  </section>
}
